[package]
name = "shell"
version = "0.1.0"
authors = ["hurrypeng"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"
libc = "0.2"
ctrlc = "3.1.7"
